[package]
name = "graphql-example"
version = "0.1.0"
authors = ["Dylan Anthony <contact@dylananthony.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.6.2"
tokio = { version = "1.4.0", features = ["rt", "macros"] }
serde_json = "1.0.64"
lamedh_runtime = "0.3.0"
lamedh_http = "0.3.0"
thiserror = "1.0.24"
aws_lambda_events = "0.4.0"
http = "0.2.3"
